### ISSUE TITLE
Issues in part of application

### ISSUE THREAD

**Issue by ashertoufeeq** [Faisal-Manzer/upcjmi-react-app#9]
There are several issues in the current application:

# No file restrictions in Sign Up
- It takes any file but only images should be allowed
- It takes a file of any size

# No CAPTCHA in the contact form
This can leave bot to spam. Also, I suggest you disable the form completely for a session.

# CAPTCHA in Sign Up form is not validating
Captcha can be any random string and it is letting to sign up. i.e. server is not validating for captcha.

**Comment by Faisal-Manzer** [comment]
Thanks for letting us know about issues.
I think you made a wrong observation, the server is validating the captcha.

We will fix other issues soon.
